/**
 * Barrel file for icon imports
 * Only imports icons actually used in the application for optimal tree-shaking
 * This reduces bundle size by ~2-3MB compared to importing entire icon libraries
 */

// Simple Icons (Si) - ~75 icons
export {
  Si1Password,
  SiAdobe,
  SiAdobeacrobatreader,
  SiAmd,
  SiAndroidstudio,
  SiApplemusic,
  SiAudacity,
  SiAudiomack,
  SiAvast,
  SiBattledotnet,
  SiBitwarden,
  SiBlender,
  SiBox,
  SiBrave,
  SiCplusplus,
  SiDbeaver,
  SiDiscord,
  SiDocker,
  SiDotnet,
  SiDropbox,
  SiEa,
  SiEpicgames,
  SiEvernote,
  SiFirefox,
  SiGimp,
  SiGit,
  SiGithub,
  SiGogdotcom,
  SiGooglechrome,
  SiIcloud,
  SiInkscape,
  SiInsomnia,
  SiIntellijidea,
  SiJetbrains,
  SiKaspersky,
  SiKdenlive,
  SiKeepassxc,
  SiLastpass,
  SiLibreoffice,
  SiMalwarebytes,
  SiMega,
  SiMusicbrainz,
  SiNeovim,
  SiNodedotjs,
  SiNordvpn,
  SiNotion,
  SiNvidia,
  SiObsidian,
  SiObsstudio,
  SiOpenjdk,
  SiOpera,
  SiOracle,
  SiPostman,
  SiProtondrive,
  SiProtonmail,
  SiProtonvpn,
  SiPycharm,
  SiPython,
  SiQbittorrent,
  SiRainmeter,
  SiRetroarch,
  SiRiotgames,
  SiSharex,
  SiSignal,
  SiSlack,
  SiSpotify,
  SiSteam,
  SiSublimetext,
  SiTelegram,
  SiThunderbird,
  SiTidal,
  SiUbisoft,
  SiVivaldi,
  SiVlcmediaplayer,
  SiVulkan,
  SiWebstorm,
  SiWhatsapp,
  SiYoutubemusic,
  SiZoom,
} from 'react-icons/si';

// Font Awesome (Fa) - ~23 icons
export {
  FaCompactDisc,
  FaDeezer,
  FaEnvelope,
  FaFileArchive,
  FaFileCode,
  FaFilePdf,
  FaFilm,
  FaGamepad,
  FaMicrosoft,
  FaPlay,
  FaSearch,
  FaShieldAlt,
  FaShieldVirus,
  FaStickyNote,
  FaTerminal,
  FaThermometerHalf,
  FaTools,
  FaVolumeUp,
  FaWrench,
} from 'react-icons/fa';

// VS Code Icons (Vsc) - 1 icon
export {
  VscCode,
} from 'react-icons/vsc';

// Feather Icons (Fi) - 1 icon (fallback)
export {
  FiPackage,
} from 'react-icons/fi';

// Custom Icons (exported from CustomIcons.jsx)
export {
  ChromeIcon,
  GoogleDriveIcon,
  WinRarIcon,
  CpuZIcon,
  GpuZIcon,
  CCleanerIcon,
  BleachBitIcon,
  DriverBoosterIcon,
  RevoUninstallerIcon,
  WinampIcon,
  EMuleIcon,
  NeroIcon,
  PowerISOIcon,
  UltraISOIcon,
  DirectXIcon,
} from './CustomIcons';
